# Cloudflare Pages 配置文件
name = "youtube-link-manager"

# 页面构建输出目录（必需的配置）
pages_build_output_dir = "."

[build]
command = ""

# KV命名空间绑定配置
# 注意：在Cloudflare Pages中，KV命名空间通过控制台绑定
# 以下配置仅用于声明绑定名称，实际ID在部署时由Cloudflare控制台配置
[[kv_namespaces]]
binding = "KV_LINKS"
# 使用空字符串作为占位符，避免构建错误
id = ""
preview_id = ""

# 注意事项：
# 1. 此文件用于声明项目配置和KV绑定需求
# 2. 实际部署时，KV_LINKS绑定需要在Cloudflare Pages控制台中手动配置
# 3. 确保在Cloudflare控制台中创建KV命名空间并绑定为KV_LINKS