# 基本的Cloudflare Pages配置
name = "youtube-link-manager"

# 构建输出目录
pages_build_output_dir = ""

# KV 命名空间配置 - 用于数据持久化
# 注意：使用正确的KV_LINKS绑定名和用户提供的命名空间ID
kv_namespaces = [
  { binding = "KV_LINKS", id = "90657b7f0780467eaa0e9ee9f55bdf92" }
]
# 由于KV_LINKS变量名在代码中已硬编码，请勿修改binding值
# 移除了preview_id，使用同一个KV命名空间ID用于生产和预览环境