# 基本的Cloudflare Pages配置
name = "youtube-link-manager"

# 构建输出目录
pages_build_output_dir = ""

# KV 命名空间配置 - 用于数据持久化
kv_namespaces = [
  { binding = "KV_LINKS", id = "YOUTUBE_LINK_KV", preview_id = "YOUTUBE_LINK_KV_PREVIEW" }
]